### PR TITLE
Add zelark's PrimeFactors kata

### PR DESCRIPTION
**Pull request by zelark**
It's my first kata.
Also I have added pom.xml.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/krrg97/vnfm/pull/5" target="_blank">ReviewNinja

**Comment by rokr97** [comment]
1. Try using gradle instead of maven.
2. Exercise solutions should stay in forked branches to avoid cheating.

**Comment by zelark** [comment]
That is we solve a kata within a week and then when Monday comes, we create a pull request?

**Comment by rokr97** [comment]
I've updated root readme file with more clearer instructions.

**Pull request closed without merging**
